---
last_check:
  etag: '"b04861e3c3b884721f7847a0e409b342"'
  version: 1.8.9
  at: 1541035053
checked_completion: true
completion_version: 1.8.8
endpoints:
  https://api.travis-ci.org/:
    access_token: 
repos:
  bokeh/bokeh:
    endpoint: https://api.travis-ci.org/
